In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.mean([73,432,53,78,4])

128.0

In [4]:
np.median([73,432,53,78,4])

73.0

In [5]:
np.average([73,432,53,78,4])

128.0

In [6]:
l = [1,2,3,4,5]

In [7]:
d_1 = np.array(l)

In [8]:
d_1

array([1, 2, 3, 4, 5])

In [9]:
d_1.ndim #Direction

1

In [10]:
d_2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [11]:
d_2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [12]:
np.array([[1,2,3,4,5],[10,20,30,40,50],['A','B','C','D','E']])

array([['1', '2', '3', '4', '5'],
       ['10', '20', '30', '40', '50'],
       ['A', 'B', 'C', 'D', 'E']], dtype='<U11')

In [13]:
d_2.ndim

2

In [14]:
d_3 = np.array([[[1,2,3,4,5],[10,20,30,40,50],['A','B','C','D','E']]])

In [15]:
d_3

array([[['1', '2', '3', '4', '5'],
        ['10', '20', '30', '40', '50'],
        ['A', 'B', 'C', 'D', 'E']]], dtype='<U11')

In [16]:
d_3.ndim

3

In [17]:
d_1

array([1, 2, 3, 4, 5])

In [18]:
d_1[0]

1

In [19]:
np.random.randint(10,20,5)

array([16, 15, 10, 10, 16])

In [20]:
np.random.randint(1,5,10)

array([2, 1, 2, 4, 2, 2, 1, 3, 4, 1])

In [21]:
np.random.random(4)

array([0.76818468, 0.85973115, 0.33462411, 0.48405772])

In [22]:
np.random.rand(3,2)

array([[0.0787218 , 0.64887237],
       [0.88046574, 0.42725169],
       [0.04729948, 0.50405769]])

In [23]:
np.random.rand(1,2)

array([[0.30052078, 0.46174907]])

In [24]:
np.random.rand(3,3)

array([[0.491598  , 0.64601784, 0.96408249],
       [0.15320077, 0.32929584, 0.63082066],
       [0.3458477 , 0.54494134, 0.51417903]])